knp_paginator:
    page_range: 5                  # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page            # Nom du paramètre de requête pour le numéro de page
        sort_field_name: sort      # Nom du paramètre de requête pour le tri
        sort_direction_name: direction # Nom du paramètre de requête pour la direction de tri
        distinct: true             # Activer ou désactiver l'option DISTINCT lors de la pagination des résultats de requête
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig' # Template Twig pour la pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # Template Twig pour les liens de tri
