#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_fo:
    path: /fo
    controller: 'App\Controller\FrontController::index'
    methods: ['GET']
app_b:
    path: /b
    controller: 'App\Controller\BackController::index'
    methods: ['GET']
app_service_apreslocation_index:
    path: /c
    controller: 'App\Controller\ServiceApreslocationController::index'
    methods: ['GET']
app_new:
    path: /new
    controller: 'App\Controller\ServiceApreslocationController::index'
    methods: ['GET']
app_z:
    path: /z
    controller: 'App\Controller\TypeController::index'
    methods: ['GET']
app_service_apreslocation_list:
    path: /list
    controller: 'App\Controller\ServiceApreslocationController::list'
    methods: ['GET']    
app_service_apreslocation_showfront:
    path: /front/{idservice}
    controller: 'App\Controller\ServiceApreslocationController::showfront'
    methods: ['GET']
app_index_front:
    path: /indexfront
    controller: 'App\Controller\FrontController::indexFront'
    methods: ['GET']
app_service_apreslocation_indexfront:
    path: /indexfront
    controller: App\Controller\ServiceApreslocationController::indexFront
    methods: ['GET']
