#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_fo:
    path: /fo
    controller: 'App\Controller\FrontController::index'
    methods: ['GET']
app_b:
    path: /b
    controller: 'App\Controller\BackController::index'
    methods: ['GET']
app_service_apreslocation_index:
    path: /c
    controller: 'App\Controller\ServiceApreslocationController::index'
    methods: ['GET']
app_new:
    path: /new
    controller: 'App\Controller\ServiceApreslocationController::index'
    methods: ['GET']
app_z:
    path: /z
    controller: 'App\Controller\TypeController::index'
    methods: ['GET']
