#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_evenement_stats:
  path: /evenement/stats/{evenement}
  controller: App\Controller\EvenementController::statistics
  methods: ["GET"]

app_login:
  path: /login
  controller: App\Controller\LoginController::login
  methods: ["GET", "POST"]
