index:
    path: /
    controller: App\Controller\DefaultController::index

app_reservation_voiture_download_pdf:
    path: '/reservation/voiture/{idR}/download-pdf'
    controller: 'App\Controller\ReservationVoitureController::downloadPdf'
    methods: ['GET']
